---
- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apk:
        name: ["git", "go", "musl-dev"]
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: /opt/FacilitatorBot
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Clone bot repository
      git:
        repo: https://github.com/SadovovAlex/FacilitatorBot.git
        dest: /opt/FacilitatorBot/repo
        force: yes

    - name: Build bot
      go_build:
        output: /opt/FacilitatorBot/bin/facilitator-bot
        package: /opt/FacilitatorBot/repo
        env:
          GOPATH: /opt/FacilitatorBot/go
          GOCACHE: /opt/FacilitatorBot/.cache/go-build

    - name: Create OpenRC init script
      template:
        src: facilitator-bot.openrc.j2
        dest: /etc/init.d/facilitator-bot
        owner: root
        group: root
        mode: '0755'

  handlers:
    - name: Enable bot service
      command: rc-update add facilitator-bot default
      changed_when: false

    - name: Start bot service
      service:
        name: facilitator-bot
        state: started
      changed_when: false
